#Presentation Settings
sitename: CSS Radar Newsletter
tagline: Weekly Newsletter For Front End Developers
desc: CSS Radar Newsletterはcssradar @ Twitterでつぶやいている最新の海外ウェブデベロップメント関連の情報をまとめてメールマガジンです。
url: http://newsletter.studiomohawk.com
#Deployment Settings
lessc: _less.js/bin/lessc
pygments:    true
markdown:    kramdown
permalink:   pretty
kramdown:
  auto_ids: false
exclude: LICENSE, README.markdown, Rakefile, .rbenv-version
