#Presentation Settings
sitename: en.ja
tagline: Translated Articles for Front End Developers
desc: フロントエンドデベロッパのためのフロントエンドデベロッパによる英記事翻訳&ログ
url: http://enja.studiomohawk.com
#Deployment Settings
lessc: _less.js/bin/lessc
pygments:    true
markdown:    kramdown
permalink:   pretty
kramdown:
  auto_ids: false
exclude: LICENSE, README.markdown, Rakefile, .rbenv-version
