#Presentation Settings
sitename: en.ja
tagline: Translated Articles for Front End Developers
desc: フロントエンドデベロッパのためのフロントエンドデベロッパによる英記事翻訳&ログ
url: http://enja.studiomohawk.com


# TOOL Settings
ga: UA-61203-18

# System Settings

pygments:    true
markdown:    kramdown
permalink:   pretty
kramdown:
  auto_ids: false
  use_coderay: true

  coderay:
    coderay_wrap: div
    coderay_line_numbers:
    coderay_tab_width: 2
    coderay_css: class

exclude: [LICENSE, README.markdown, jakefile, .rbenv-version, tasks, node_modules, npm-debug.log, package.json, grunt.js, Gruntfile.js, grunt-aws.json]
include: [_includes]
